const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const screenshotDir = process.env.UI_SCREENSHOT_DIR || '/tmp/elections26-ui';
fs.mkdirSync(screenshotDir, {recursive:true});
const baseUrl = process.env.UI_BASE_URL || 'http://127.0.0.1:5173/';
const meta = require('../src/data/meta.json');
const ids=meta.lists2026.map(l=>l.id);
const cells=Object.fromEntries(ids.map(id=>[id,{v:id==='likud'?120:0,src:'manual',locked:false}]));
const stat=(list,mean,min=mean,max=mean)=>({list,n:2,mean,min,max,median:mean,p25:min,p75:max});
const dashboard={participants:2,open:true,publishedAt:'2026-10-07',aggregationId:'demo',seats:{n:2,full:[stat('likud',30,28,32),stat('rzp',6)],polls:{likud:28,rzp:5},pctStats:[stat('likud',24.5,23,26),stat('rzp',4.5)],modes:{seats:0,pct:2}},blocs:{derived:{gov:stat('gov',60,58,62),rest:stat('rest',60)},customCount:0,custom:[],explicit:null},vote2022:{all:{'ט':{n:2,of:2}},valid:{},official:{}},vote2026:{all:{rzp:{n:2,of:2}},named:{}},matrix:{publishedAt:'2026-10-07',rows:{'ט':{n:2,cells:{rzp:{n:2,of:2}}}}}};
const tok='abcdefghijklmnopqrstuv';
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.UI_BROWSER_EXECUTABLE,args:['--no-sandbox']});
for(const theme of ['league','board']) for(const width of [360,820,1280]){
 const context=await browser.newContext({viewport:{width,height:1000},hasTouch:true});
 const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({theme,cells,tok})=>{
  localStorage.setItem('elections26.theme',theme);
  localStorage.setItem('elections26.crowd.token','test-session');
  localStorage.setItem('elections26.crowd.link','test-personal-link');
  localStorage.setItem('elections26.crowd.intro','1');
  localStorage.setItem('elections26.crowd.linkAck','1');
  localStorage.setItem('elections26.crowd.draft.seats',JSON.stringify({seats:cells,start:'zero',pollsAsOf:null}));
  localStorage.setItem('elections26.crowd.saved.blocs',JSON.stringify({mode:'gov37',blocs:[{id:'gov',name:'ממשלה',lists:['likud'],target:null},{id:'rest',name:'יתר',lists:[],target:null}]}));
  localStorage.setItem('elections26.feedback',JSON.stringify([{token:tok,created:'2026-10-01',preview:'הודעה ישנה לדוגמה'}]));
 },{theme,cells,tok});
 await page.route('https://crowd.example/**',async route=>{
  const p=new URL(route.request().url()).pathname;
  const data=p==='/me'?{participant:'demo',username:'דוגמה',latest:{},created_at:'2026-10-01'}:p==='/support'?{thread:null}:p==='/dashboard'?dashboard:{};
  await route.fulfill({json:data});
 });
 await page.route('https://feedback.example/**',route=>route.fulfill({json:{ok:true,topic:'design',text:'הודעה ישנה לדוגמה',status:'answered',created_at:'2026-10-01',messages:[{author:'team',text:'תשובת צוות לדוגמה',created_at:'2026-10-02'}]}}));
 await page.goto(`${baseUrl}#/support`);
 await page.getByText('תשובת צוות לדוגמה',{exact:true}).waitFor();
 await page.getByText('מחוברים בשם').waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow support ${theme} ${width}`);
 await page.screenshot({path:`${screenshotDir}/support-${theme}-${width}.png`,fullPage:true});
 await page.goto(`${baseUrl}#/feedback/${tok}`);
 await page.getByText('תשובת צוות לדוגמה',{exact:true}).waitFor();
 assert.ok(page.url().includes('/feedback/'));
 await page.goto(`${baseUrl}#/guess`);
 await page.locator('[data-bloc-id="coalition"]').waitFor();
 assert.equal(await page.locator('[data-bloc-id]').count(),4);
 assert.equal(await page.locator('[data-bloc-party] select').count(),0);
 assert.equal(await page.getByRole('button',{name:'עריכת שמות הגושים',exact:true}).count(),0);
 await page.getByRole('button',{name:'עריכת שם הגוש: הקואליציה הנוכחית',exact:true}).click();
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).fill('שם אישי');
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).press('Enter');
 await page.getByRole('button',{name:'עריכת שם הגוש: שם אישי',exact:true}).click();
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).fill('ביטול');
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).press('Escape');
 assert.equal(await page.getByRole('button',{name:'עריכת שם הגוש: שם אישי',exact:true}).count(),1);
 await page.getByRole('button',{name:'עריכת שם הגוש: שם אישי',exact:true}).click();
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).fill('הקואליציה הנוכחית');
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).press('Tab');
 await page.locator('[data-bloc-party="likud"] button').scrollIntoViewIfNeeded();
 let source=await page.locator('[data-bloc-party="likud"] button').boundingBox();
 let target=await page.locator('[data-bloc-id="opposition"]').boundingBox();
 await page.mouse.move(source.x+20,source.y+20); await page.mouse.down();
 await page.mouse.move(target.x+target.width/2,target.y+30,{steps:8});
 assert.equal(await page.locator('[data-drag-preview="likud"]').count(),1);
 await page.mouse.up();
 assert.equal(await page.locator('[data-bloc-id="opposition"] [data-bloc-party="likud"]').count(),1);
 await page.locator('[data-bloc-party="likud"] button').press('ArrowLeft');
 assert.equal(await page.locator('[data-bloc-id="arabs"] [data-bloc-party="likud"]').count(),1);
 // עריכת שמות אינה מתבצעת אוטומטית בעקבות העברה.
 assert.equal(await page.locator('[data-bloc-id="coalition"] h3').innerText(),'הקואליציה הנוכחית');
 await page.locator('[data-bloc-party="likud"] button').scrollIntoViewIfNeeded();
 source=await page.locator('[data-bloc-party="likud"] button').boundingBox();
 target=await page.locator('[data-bloc-id="new"]').boundingBox();
 const cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:source.x+20,y:source.y+20}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:target.x+target.width/2,y:Math.max(160,Math.min(target.y+30,850))}]});
 assert.equal(await page.locator('[data-drag-preview="likud"]').count(),1);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await page.locator('[data-bloc-id="new"] [data-bloc-party="likud"]').waitFor({timeout:5000});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow guess ${theme} ${width}`);
 await page.locator('[data-bloc-id="coalition"]').scrollIntoViewIfNeeded();
 await page.screenshot({path:`${screenshotDir}/blocs-${theme}-${width}.png`});
 await page.getByRole('button',{name:'סטטיסטיקות',exact:true}).click();
 await page.getByRole('radio',{name:'אחוזים',exact:true}).click();
 await page.getByRole('heading',{name:'אחוזים',exact:true}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'גושים',exact:true}).count(),1);
 assert.ok((await page.locator('#statistics').innerText()).includes('24.5%'));
 assert.ok((await page.locator('#statistics').innerText()).includes('לא שינו בחירה: 2'));
 await page.getByRole('radio',{name:'גרף',exact:true}).click();
 assert.equal(await page.getByRole('heading',{name:'גושים',exact:true}).count(),1);
 assert.equal(errors.length,0,errors.join('\n'));
 console.log(`${theme} ${width}: עברו: שיחות קודמות, ארבעה גושים, גרירה בעכבר ובמגע, מקלדת, אחוזים וגושים קבועים`);
 await context.close();
}
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
