const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const screenshotDir = process.env.UI_SCREENSHOT_DIR || '/tmp/elections26-ui';
fs.mkdirSync(screenshotDir, {recursive:true});
const baseUrl = process.env.UI_BASE_URL || 'http://127.0.0.1:5173/';
const meta = require('../src/data/meta.json');
const ids=meta.lists2026.map(l=>l.id);
const cells=Object.fromEntries(ids.map(id=>[id,{v:id==='likud'?120:0,src:'manual',locked:false}]));
const stat=(list,mean,min=mean,max=mean)=>({list,n:2,mean,min,max,median:mean,p25:min,p75:max});
const dashboard={sectionParticipants:{seats:2,blocs:2,vote2026:2,vote2022:2},participants:2,open:true,publishedAt:'2026-10-07',aggregationId:'demo',seats:{n:2,full:[stat('likud',30,28,32),stat('rzp',6)],polls:{likud:28,rzp:5},pctStats:[stat('likud',24.5,23,26),stat('rzp',4.5)],modes:{seats:0,pct:2}},blocs:{derived:{gov:stat('gov',60,58,62),rest:stat('rest',60)},customCount:2,custom:[{name:"שם אישי שאין להציג",lists:["joint","raam"],n:2,explicit:null,derived:stat("arabs",13)}],explicit:null},vote2022:{all:{'ט':{n:2,of:2}},valid:{},official:{}},vote2026:{all:{rzp:{n:2,of:2}},named:{}},matrix:{publishedAt:'2026-10-07',rows:{'ט':{n:2,cells:{rzp:{n:2,of:2}}}}}};
const tok='abcdefghijklmnopqrstuv';
async function dragCard(page, source, destination, cdp) {
 await source.evaluate(el=>el.scrollIntoView({block:'center'}));
 const from=await source.boundingBox();
 const move=async (x,y)=>cdp ? cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y}]}) : page.mouse.move(x,y,{steps:4});
 if(cdp) await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:from.x+20,y:from.y+20}]});
 else { await page.mouse.move(from.x+20,from.y+20); await page.mouse.down(); }
 await move(from.x+30,from.y+20);
 let reached=false;
 for(let i=0;i<100;i++) {
  const to=await destination.boundingBox(); const height=page.viewportSize().height;
  const y=to.y+Math.min(25,to.height/2);
  const x=Math.max(20,Math.min(page.viewportSize().width-20,to.x+to.width/2));
  if(y>160 && y<height-250){await move(x,y);await page.waitForTimeout(80);const final=await destination.boundingBox();await move(x,final.y+Math.min(25,final.height/2));reached=true;break;}
  await move(x,y<=160?40:height-40); await page.waitForTimeout(100);
 }
 assert.ok(reached,'auto-scroll reaches drop destination');
 if(cdp) await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]}); else await page.mouse.up();
}
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.UI_BROWSER_EXECUTABLE,args:['--no-sandbox']});
for(const theme of ['league','board']) for(const width of [360,820,1280]){
 const context=await browser.newContext({viewport:{width,height:1000},hasTouch:true});
 const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({theme,cells,tok,ids})=>{
  localStorage.setItem('elections26.theme',theme);
  localStorage.setItem('elections26.crowd.token','test-session');
  localStorage.setItem('elections26.crowd.link','test-personal-link');
  localStorage.setItem('elections26.crowd.intro','1');
  localStorage.setItem('elections26.crowd.linkAck','1');
  localStorage.setItem('elections26.crowd.draft.seats',JSON.stringify({seats:cells,start:'zero',pollsAsOf:null}));
  localStorage.setItem('elections26.crowd.saved.blocs',JSON.stringify({mode:'custom',blocs:[{id:'coalition',name:'הקואליציה הנוכחית',lists:['likud'],target:null},{id:'opposition',name:'האופוזיציה הנוכחית',lists:ids.filter(id=>id!=='likud'),target:null},{id:'arabs',name:'ערבים',lists:[],target:null},{id:'new',name:'חדשות',lists:[],target:null}]}));
  localStorage.setItem('elections26.feedback',JSON.stringify([{token:tok,created:'2026-10-01',preview:'הודעה ישנה לדוגמה'}]));
 },{theme,cells,tok,ids});
 const crowdRoute = async route=>{
  const p=new URL(route.request().url()).pathname.replace(/^\/crowd/, '');
  const data=p==='/me'?{participant:'demo',username:'דוגמה',latest:{},created_at:'2026-10-01'}:p==='/support'?{thread:null}:p==='/dashboard'?dashboard:{};
  await route.fulfill({json:data});
 };
 await page.route('https://crowd.example/**',crowdRoute);
 await page.route('https://feedback.example/crowd/**',crowdRoute);
 await page.route('https://feedback.example/**',route=>new URL(route.request().url()).pathname.startsWith('/crowd/') ? crowdRoute(route) : route.fulfill({json:{ok:true,topic:'design',text:'הודעה ישנה לדוגמה',status:'answered',created_at:'2026-10-01',messages:[{author:'team',text:'תשובת צוות לדוגמה',created_at:'2026-10-02'}]}}));
 await page.goto(`${baseUrl}#/support`);
 await page.getByText('תשובת צוות לדוגמה',{exact:true}).waitFor();
 await page.getByText('מחוברים בשם').waitFor();
 assert.equal(await page.locator('textarea').count(),1,'one support composer');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow support ${theme} ${width}`);
 await page.screenshot({path:`${screenshotDir}/support-${theme}-${width}.png`,fullPage:true});
 await page.evaluate(()=>localStorage.removeItem('elections26.crowd.token'));
 await page.reload();
 await page.getByText('אפשר לכתוב לנו גם בלי חשבון.',{exact:true}).waitFor();
 assert.equal(await page.locator('textarea').count(),1,'anonymous composer');
 await page.getByRole('textbox',{name:'הודעה לתמיכה'}).fill('בדיקת פנייה בלי חשבון');
 await page.getByRole('button',{name:'שליחת הודעה',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#support-message').value==='');
 await page.evaluate(()=>localStorage.setItem('elections26.crowd.token','test-session'));
 await page.goto(`${baseUrl}#/feedback/${tok}`);
 await page.getByText('תשובת צוות לדוגמה',{exact:true}).waitFor();
 assert.ok(page.url().includes('/feedback/'));
 await page.goto(`${baseUrl}#/guess`);
 assert.equal(await page.locator('[data-bloc-id]').count(),0,'לשונית מנדטים אינה מציגה גושים');
 await page.getByRole('heading',{name:'הגושים שלי',exact:true}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'הגושים שלי',exact:true}).count(),1);
 assert.equal(await page.locator('[data-personal-blocs-card]').count(),1);
 const targetInput=page.getByRole('spinbutton',{name:'מנדטים צפויים לגוש הקואליציה הנוכחית',exact:true});
 await targetInput.fill('61');
 assert.equal(await targetInput.inputValue(),'61');
 assert.equal(await page.locator('[data-bloc-pool]').count(),0,'target editing does not embed the composition editor');
 await targetInput.fill('');
 const resetButton=page.getByRole('button',{name:'אפס הכול',exact:true});
 const resetBox=await resetButton.boundingBox();
 const actionBox=await resetButton.locator('../..').boundingBox();
 assert.ok(Math.abs((resetBox.x+resetBox.width/2)-(actionBox.x+actionBox.width/2))<2,'reset centered');
 await resetButton.click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'reset confirmation overflow');
 await page.getByRole('button',{name:'לא',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'אפס הכול',exact:true}).count(),1);
 await page.getByRole('button',{name:'לפי גושים',exact:true}).click();
 assert.deepEqual(await page.locator('nav[aria-label="חלקי ההשערה"] button').allTextContents(),['לפי מנדטים','לפי אחוזים','לפי גושים','ההצבעה שלי','ההיסטוריה שלי']);
 await page.locator('[data-bloc-id="coalition"]').waitFor();
 assert.equal(await page.locator('[data-bloc-id]').count(),4);
 assert.equal(await page.locator('[data-bloc-party] select').count(),0);
 assert.equal(await page.getByRole('button',{name:'עריכת שמות הגושים',exact:true}).count(),0);
 await page.getByRole('button',{name:'עריכת שם הגוש: הקואליציה הנוכחית',exact:true}).click();
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).fill('שם אישי');
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).press('Enter');
 await page.getByRole('button',{name:'עריכת שם הגוש: שם אישי',exact:true}).click();
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).fill('ביטול');
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).press('Escape');
 assert.equal(await page.getByRole('button',{name:'עריכת שם הגוש: שם אישי',exact:true}).count(),1);
 await page.getByRole('button',{name:'עריכת שם הגוש: שם אישי',exact:true}).click();
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).fill('הקואליציה הנוכחית');
 await page.getByRole('textbox',{name:'שם הגוש 1',exact:true}).press('Tab');
 await page.locator('[data-bloc-id="coalition"] [data-bloc-party="likud"] [data-party-drag]').evaluate(el=>el.scrollIntoView({block:"center"}));
 let source=await page.locator('[data-bloc-id="coalition"] [data-bloc-party="likud"] [data-party-drag]').boundingBox();
 let target=await page.locator('[data-bloc-id="opposition"]').boundingBox();
 await page.mouse.move(source.x+20,source.y+20); await page.mouse.down();
 await page.mouse.move(target.x+target.width/2,target.y+30,{steps:8});
 assert.equal(await page.locator('[data-drag-preview="likud"]').count(),1);
 await page.mouse.up();
 await page.locator('[data-bloc-id="opposition"] [data-bloc-party="likud"]').waitFor();
 await page.locator('[data-bloc-id="opposition"] [data-bloc-party="likud"] [data-party-drag]').press('ArrowLeft');
 assert.equal(await page.locator('[data-bloc-id="arabs"] [data-bloc-party="likud"]').count(),1);
 // עריכת שמות אינה מתבצעת אוטומטית בעקבות העברה.
 assert.equal(await page.locator('[data-bloc-id="coalition"] h3').innerText(),'הקואליציה הנוכחית');
 await page.locator('[data-bloc-id="arabs"] [data-bloc-party="likud"] [data-party-drag]').evaluate(el=>el.scrollIntoView({block:"center"}));
 source=await page.locator('[data-bloc-id="arabs"] [data-bloc-party="likud"] [data-party-drag]').boundingBox();
 target=await page.locator('[data-bloc-id="new"]').boundingBox();
 const cdp=await context.newCDPSession(page);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:source.x+20,y:source.y+20}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:target.x+target.width/2,y:Math.max(160,Math.min(target.y+30,850))}]});
 assert.equal(await page.locator('[data-drag-preview="likud"]').count(),1);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await page.locator('[data-bloc-id="new"] [data-bloc-party="likud"]').waitFor({timeout:5000});
 assert.equal(await page.locator('[data-bloc-id="coalition"] [data-bloc-party="likud"]').count(),1,'copy preserves source');
 await page.getByRole('button',{name:'הוספת גוש (4/5)',exact:true}).click();
 assert.equal(await page.locator('[data-bloc-id]').count(),5);
 assert.equal(await page.getByRole('button',{name:'הוספת גוש (5/5)',exact:true}).isDisabled(),true);
 const fifth=page.locator('[data-bloc-id]').last();
 await fifth.getByRole('button',{name:'מחיקת הגוש',exact:true}).click();
 assert.equal(await page.locator('[data-bloc-id]').count(),4);
 assert.equal(await page.getByRole('radio',{name:'לפי אחוזי הצבעה',exact:true}).count(),0);
 const pool=page.locator('[data-bloc-pool]');
 assert.equal(await pool.locator('[data-bloc-party]').count(),ids.length,'pool always contains every party');
 const arabs=page.locator('[data-bloc-id="arabs"]');
 await arabs.locator('[data-bloc-party="likud"] [data-party-drag]').press('Delete');
 assert.equal(await arabs.locator('[data-bloc-party="likud"]').count(),0);
 assert.equal(await page.locator('[data-bloc-id="coalition"] [data-bloc-party="likud"]').count(),1);
 const poolLikud=pool.locator('[data-bloc-party="likud"] [data-party-drag]');
 await dragCard(page,poolLikud,arabs.locator('h3'));
 await arabs.locator('[data-bloc-party="likud"]').waitFor();
 await dragCard(page,poolLikud,arabs.locator('h3'));
 assert.equal(await arabs.locator('[data-bloc-party="likud"]').count(),1,'adding twice does not duplicate');
 await dragCard(page,arabs.locator('[data-bloc-party="likud"] [data-party-drag]'),pool.locator('h3'),cdp);
 assert.equal(await arabs.locator('[data-bloc-party="likud"]').count(),0,'touch drag out removes only source');
 assert.equal(await page.locator('[data-bloc-id="opposition"] [data-bloc-party="likud"]').count(),1);
 assert.equal(await pool.locator('[data-bloc-party]').count(),ids.length);
 const coalitionCard=page.locator('[data-bloc-id="coalition"] [data-bloc-party="likud"] [data-party-drag]');
 await coalitionCard.click();
 assert.equal(await page.locator('[data-drag-preview]').count(),0,'tap is not a drag');
 await coalitionCard.evaluate(el=>el.scrollIntoView({block:'center'}));
 const cancelBox=await coalitionCard.boundingBox();
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cancelBox.x+20,y:cancelBox.y+20}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cancelBox.x+20,y:40}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
 assert.equal(await page.locator('[data-bloc-id="coalition"] [data-bloc-party="likud"]').count(),1,'cancelled drag preserves membership');
 assert.equal(await page.locator('[data-drag-preview]').count(),0);
 await poolLikud.press('ArrowLeft');
 assert.equal(await page.locator('[data-bloc-id="coalition"] [data-bloc-party="likud"]').count(),1);
 await page.locator('[data-bloc-id="new"]').getByRole('button',{name:'הסרת הליכוד מהגוש',exact:true}).click();
 assert.equal(await page.locator('[data-bloc-id="new"] [data-bloc-party="likud"]').count(),0,'button removal');
 await dragCard(page,poolLikud,page.locator('[data-bloc-id="new"] h3'),cdp);
 await page.locator('[data-bloc-id="new"] [data-bloc-party="likud"]').waitFor();
 await dragCard(page,page.locator('[data-bloc-id="new"] [data-bloc-party="likud"] [data-party-drag]'),page.locator('nav[aria-label="חלקי ההשערה"]'));
 assert.equal(await page.locator('[data-bloc-id="new"] [data-bloc-party="likud"]').count(),0,'drag outside all blocs removes source');
 assert.equal(await pool.locator('[data-bloc-party]').count(),ids.length);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow guess ${theme} ${width}`);
 await page.locator('[data-bloc-id="coalition"]').scrollIntoViewIfNeeded();
 await page.screenshot({path:`${screenshotDir}/blocs-${theme}-${width}.png`});
 await page.getByRole('button',{name:'סטטיסטיקות',exact:true}).click();
 await page.getByRole('radio',{name:'אחוזים',exact:true}).click();
 await page.getByRole('heading',{name:/אחוזים.*משתתפים/}).waitFor();
 assert.equal(await page.getByRole('heading',{name:/גושים.*משתתפים/}).count(),1);
 assert.ok((await page.locator('#statistics').innerText()).includes(' · '));
 assert.equal((await page.locator('#statistics').innerText()).includes('שם אישי שאין להציג'),false);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow statistics ${theme} ${width}`);
 await page.screenshot({path:`${screenshotDir}/statistics-${theme}-${width}-${await page.getByRole('radio',{name:'גרף',exact:true}).getAttribute('aria-checked')}.png`});
 assert.equal(await page.locator('#statistics').getByText('2 משתתפים',{exact:true}).count(),3,'per-section contributor headings');
 assert.ok((await page.locator('#statistics').innerText()).includes('24.5%'));
 assert.ok((await page.locator('#statistics').innerText()).includes('לא שינו בחירה: 2'));
 await page.getByRole('radio',{name:'גרף',exact:true}).click();
 assert.equal(await page.getByRole('heading',{name:/גושים.*משתתפים/}).count(),1);
 assert.ok((await page.locator('#statistics').innerText()).includes(' · '));
 assert.equal((await page.locator('#statistics').innerText()).includes('שם אישי שאין להציג'),false);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow statistics ${theme} ${width}`);
 await page.screenshot({path:`${screenshotDir}/statistics-${theme}-${width}-${await page.getByRole('radio',{name:'גרף',exact:true}).getAttribute('aria-checked')}.png`});
 assert.equal(errors.length,0,errors.join('\n'));
 console.log(`${theme} ${width}: עברו: שיחות קודמות, חמישה גושים עצמאיים, העתקה בגרירה בעכבר ובמגע, מקלדת, אחוזים וגושים קבועים`);
 await context.close();
}
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
